spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: storage
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: 'classpath:db/changelog/changeLog.xml'
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1